version: 1
domain: tax
created_by: RIFAZ-SOLUTIONS
seed_examples:
  - context: |
      1ps. 1ps. ## UNITED REPUBLIC OF TANZANIA TANZANIA REVENUE AUTHORITY ## APPLICATION FOR PRIVATE OR CLASS RULING Date 20 This form is for use by all taxpayers;, either personally or by their authorised agent; applying for a ruling on a proposed; current or completed arrangement: ## Applicants details Complete the details of the persons to whom this ruling will apply; If there are not enough spaces, use a separate sheet of paper and attach it to this form. Full name of Applicant. TIN: Full name of Applicant - TIN: Full name of Applicant. TIN: ## Agent details If this application is made on behalf of an applicant(s) the agent must have written consent 2ps. from the applicant(s) The written consent must be supplied on request to the Tanzania Revenue Authority . 2ps. 1ps. Full name of Applicant. TIN: Full name of Applicant - TIN: Full name of Applicant. TIN: ## Agent details If this application is made on behalf of an applicant(s) the agent must have written consent from the applicant(s) The written consent must be supplied on request to the Tanzania Revenue Authority . Full name of Taxpayer's Representative Taxpayer's Representative business name\_ Taxpayer Identification Number of the Taxpayer's representative Contact person for enquiries Full name Office phone number(s) Email address Physical address \_ Postal address\_ Townlcity . ## General questions - 1 If you have previously applied for a ruling in respect of this transaction please advise the reference number or final ruling number - 2 Have you 2ps. previously received any other advice from Tanzania Revenue Authority on this transaction? If yes, please provide details in your application: - 3 Is this an application for a transfer pricing arrangement?
    questions_and_answers:
      - question: |
          What is the purpose of the form mentioned in the context?
        answer: |
          The form is for taxpayers or their authorized agents to apply for a ruling on a proposed, current, or completed arrangement with the Tanzania Revenue Authority.
      - question: |
          What must an agent provide when making an application on behalf of a taxpayer?
        answer: |
          The agent must have written consent from the taxpayer(s), which must be supplied upon request to the Tanzania Revenue Authority.
      - question: |
          What details are required for the taxpayer's representative in the application?
        answer: |
          The application requires the full name, business name, Taxpayer Identification Number, contact person's name, office phone number(s), email address, physical address, postal address, and town/city of the taxpayer's representative.
      - question: |
          What additional information is requested if a ruling has been applied for previously?
        answer: |
          If a ruling has been applied for previously, the applicant is asked to provide the reference number or final ruling number.
      - question: |
          What specific question is asked regarding transfer pricing arrangements?
        answer: |
          The form asks if the application is for a transfer pricing arrangement.
document_outline: |
  **Document Outline:**  
  The document is an official application form provided by the Tanzania Revenue Authority for taxpayers or their authorized agents to request a private or class tax ruling on proposed, current, or completed arrangements. It includes sections for applicant and agent details, clarifying questions regarding the transaction, a declaration of truthfulness, a checklist to ensure all necessary information is provided, and submission instructions.
document:
  repo: https://github.com/RIFAZ-SOLUTIONS/dataprepai.git
  commit: 1e7334d
  patterns:
    - ApplicationForPrivateClassRuling.md
