version: 1
domain: tax
created_by: RIFAZ-SOLUTIONS
seed_examples:
  - context: |
      1ps. 1ps. C.12
      
      ## EAST AFRICAN COMMUNITY                                                 
                               CUSTOMS
      
      Regulation 49 (1)
      
      ## APPLICATION FOR RELEASE
         OF PERISHABLES OR OTHER GOODS PRIOR TO PAYMENT OF DUTY
      
      To The Proper
         Officer,      
      
      2ps.                                                                   Port
         …………………………
      
      at…………………………..           
                             
      
      3ps.                                    Date.  ………………20….…
      
      I
         request
      
      permission
      
      to
      
      remove,
      
      the
      
      under-mentioned
      
      goods
      
      imported
      
      in
      
      aircraft/vessel/vehicle…………………………..on
         …………20…..… prior to payment of duties
      
      and other taxes. 
      
      Marks
         and
         numbers…………………………….…………………………..………………………….
         
      
      Number and description of
         packages……………………..…………………………………………
      
      ……………………………………………………………………………………………………………
      
      Description
         of
         goods..
      
      ……………………………………………………………………………………………………………
      
      ……………………………………………………………………………………………………………
      
      ……………………………………………………………………………………………………………
      
      Value
         in
         dollars….……………………………………………………………………………………..
      
      …………………………………
      
      Importer/Agent.
         
      
      ## RELEASE APPROVED
      
      *Bond given on CB1.  N0.  ……….  /Cash Deposited
         on
         Receipt…………………
      
      Dated………20……
      
      ……………………………….
         
      
      Proper officer. 
      
      Released…………………………………….
         
      
      Signature
      
      Stamp of releasing officer.
      
      
      
      
    questions_and_answers:
      - question: |
          What is the purpose of Regulation 49 (1) under the East African Community Customs?
        answer: |
          Regulation 49 (1) allows for the release of perishable goods or other imported items prior to payment of duties and other taxes.
      - question: |
          Who can approve the release of goods under this regulation?
        answer: |
          The release of goods under this regulation can be approved by a 'Proper Officer' who is authorized to grant permission.
      - question: |
          What are some of the details required in the application for the release of goods?
        answer: |
          The application must include marks and numbers, the number and description of packages, the description of goods, their value in dollars, and the importing aircraft, vessel, or vehicle.
      - question: |
          What forms of security might be required for the release of goods prior to duty payment?
        answer: |
          Security in the form of a bond (CB1) or a cash deposit is required for the release of goods prior to duty payment.
      - question: |
          What documentation is involved once the goods are approved for release?
        answer: |
          Once approved, the release involves the signature and stamp of the releasing officer, along with documentation of the bond or cash deposit details.
document_outline: |
  **Document Outline:**  
  The document is a formal application form under the East African Community Customs Regulation 49 (1). It is used by importers or agents to request permission for the early release of perishable or other imported goods prior to the payment of duties and taxes. The form requires details about the goods, their value, and confirmation of bond or cash deposit, along with approval by a proper customs officer.
document:
  repo: https://github.com/RIFAZ-SOLUTIONS/dataprepai.git
  commit: 1e7334d
  patterns:
    - c12-application-release-perishables-or-other-goods-prior-to-payment-of-duty.md
