version: 1
domain: tax
created_by: RIFAZ-SOLUTIONS
seed_examples:
  - context: |
      1ps. 1ps. C.2 2
      
      ## EAST AFRICAN COMMUNITY                                                
                                                  CUSTOMS
      
      Regulation 94 (1)
      
      ##
         APPLICATION TO SHIP
      
      2ps. GOODS PRIOR TO ENTRY
      
      Rotation No. ……………….. 
      
      Port  of
         ……………..………
      
      Country ……………………. 
      
      *I/We, the
         undersigned, request permission to ship prior to entry the following goods by
         the
      
      *aircraft/vessel …………………………….  on or about the
         …………day of ………….……….20…..
      
      ## PARTICULARS OF
         GOODS
      
      Packages:
      
      Marks and numbers
         ………………………………………………………………………………….
         
      
      Number and description
         ……………………………………………………………………………..
         
      
      Description of goods
         ………………………………………………………………………………………
      
      Weight
         or quantity ……………………………
      
      Value in dollars
         ……………………………………
      
      Name and address of consignee
         ………………………………………………………………………….
         
      
      Destination of goods
         ………………………………………………………………………………………..
      
      *I/We
         declare that the above particulars are true and *I/we undertake to furnish
         the necessary entry and pay the duty due, if any, on the above-mentioned
         goods within ninety-six hours of the departure of the aircraft or
      
      3ps. vessel. 
      
      Date ……………………20….  ..                               
                               
         …………………………………..
      
      Exporter
      
      Bond in force/Cash
         deposit in
         dollars…………………………………………………………………….
         
      
      *Approved/Not approved
      
      Date ……………………20….  …           
                           
      
      4ps.                        …………………………….……
      
      Proper Officer
      
      
      
      
    questions_and_answers:
      - question: |
          What is the purpose of Regulation 94 (1) under the East African Community Customs framework?
        answer: |
          Regulation 94 (1) allows exporters to apply for permission to ship goods prior to entry, provided that they undertake to furnish the necessary entry documents and pay any applicable duty within 96 hours of the departure of the aircraft or vessel.
      - question: |
          What information must be provided about the goods in the application form?
        answer: |
          The applicant must provide details about the packages, marks and numbers, description of goods, weight or quantity, value in dollars, the name and address of the consignee, and the goods' destination.
      - question: |
          What is the applicant’s obligation after receiving approval to ship goods prior to entry?
        answer: |
          The applicant must ensure that the necessary entry documents are furnished and any corresponding duty is paid within 96 hours of the departure of the transport vessel or aircraft.
      - question: |
          What financial safeguards are mentioned in this regulation for applying to ship goods prior to entry?
        answer: |
          The application mentions the option of a bond in force or a cash deposit in dollars as a financial safeguard.
      - question: |
          Who reviews and approves or denies the application to ship goods prior to entry?
        answer: |
          The application is reviewed and approved or denied by a Proper Officer from the East African Community Customs.
document_outline: |
  **Document Outline:**  
  The document outlines a formal application process under Regulation 94 (1) of the East African Community Customs regulations, enabling exporters to request permission to ship goods prior to their customs entry. It includes details about the goods, consignee, vessel, and exporter’s declaration, along with provisions for approval by a customs officer.
document:
  repo: https://github.com/RIFAZ-SOLUTIONS/dataprepai.git
  commit: 1e7334d
  patterns:
    - c22-application-ship-goods-prior-to-entry.md
