version: 1
domain: tax
created_by: RIFAZ-SOLUTIONS
seed_examples:
  - context: |
      1ps. 1ps. C. 23
      
      ## EAST AFRICAN COMMUNITY                                                
                                                       
      
      2ps.                                     CUSTOMS
      
      Regulation 95 (1)
      
      ## APPLICATION
         TO RELOAD GOODS UNLOADED IN ERROR
      
      To the Proper Officer,
      
      For Official
         Use
      
      Rotation No. ………………………………
      
      Date
         ………………………………………. 
      
      Permission is hereby
         requested to reload into *aircraft/vessel
         ………………………………………………………. 
      
      lying at
         ……………………………………………… the following goods
         unloaded there from in error. 
      
      Marks and numbers of packages
      
      Description of
         goods
      
      ……………………………………..
      
      Master
      
      Permission is
         granted subject to the following
         conditions:
      
      ……………………….…………………………………
      
      ………………………………………………………….
         
      
      …………………………………. 
      
      Proper Officer
      
      Received on
         board the above-mentioned
         goods
      
      ………………………………………..
      
      Master
      
      Date
         ………………………………….
      
      
      
      
    questions_and_answers:
      - question: |
          What is the purpose of the document within the East African Community Customs regulations?
        answer: |
          The document is used to request permission to reload goods that were unloaded in error onto the same aircraft or vessel.
      - question: |
          Who is the request for reloading goods addressed to?
        answer: |
          The request is addressed to the Proper Officer as part of the Customs process.
      - question: |
          What detailed information must be included in the request for reloading goods?
        answer: |
          The request must include the rotation number, date, details of the aircraft or vessel, location, and the marks, numbers, and description of the packages.
      - question: |
          Who provides approval for reloading the goods, and under what conditions?
        answer: |
          The Proper Officer provides approval for reloading the goods, subject to specific conditions outlined in the document.
      - question: |
          Who confirms that the goods have been reloaded onto the aircraft or vessel?
        answer: |
          The Master of the aircraft or vessel confirms the reloading of the goods by signing and dating the document.
document_outline: |
  **Document Outline:**  
  This document pertains to Regulation 95(1) under the East African Community Customs framework, detailing the application process for reloading goods that were mistakenly unloaded from an aircraft or vessel. It includes fields for official use, details about the goods, and permissions granted by the Proper Officer under specified conditions.
document:
  repo: https://github.com/RIFAZ-SOLUTIONS/dataprepai.git
  commit: 1e7334d
  patterns:
    - c23-application-transfer-stores-of-aircraft-or-vessel.md
