version: 1
domain: tax
created_by: RIFAZ-SOLUTIONS
seed_examples:
  - context: |
      1ps. 1ps. CUSTOMS
      
      Regulation 210 (1)
      
      ## APPLICATION FOR LICENSING VESSELS/VEHICLE FOR
         CONVEYANCE OF GOODS UNDER CUSTOMS CONTROL
      
      To the Commissioner  
         ………………………………………………………………………………………………
      
      ##
         1. Details of vehicle owner
      
      Names(s)
         ……………………………..…………… P.O.Box No.
         …………….……… Telephone  ………….…
      
      Fax No.
         ………………….     Country of registration
         ………………………  mail Address ………….…………
      
      ## 2.
         Details of Application
      
      Names
         ……………………………………………………  Postal Address
         ………………………………………. 
      
      Passport Number
         ……………………………………….    Telephone
         ……………………………………………. 
      
      ## 3. Motor Vehicle
         Registration Details
      
      Engine number
         ………………………………………….    Chassis Number
         …………………………………….. 
      
      Vehicle Registration Number
         ………………………..…  Model …………………
         Colour……………...………. 
      
      Year of manufacture ……………
         Mileage  ……………….    Weight of empty vehicle (Tare)
         …...……………
      
      ##
      
      2ps. 4. Logbook and Vehicle Insurance Details
      
      Logbook No. …………………..  
         Original (tick) ………………………….   Certified copy (tick)
         ………………..
      
      3 rd
      
      party policy No.
         ………………………………..   Insurance Company
         ………………………………………. 
      
      Valid Sticker No?   Yes
         ……………….   No ………………..   Serial No …………….   
         Date of expiry ………...
      
      ## 5. Declaration by the applicant
      
      I,
         undersigned, declare that the particulars stated above are true and correct.
         
      
      Names
         ………………………………………………………………  
         Signature …………………………………..
      
      ## 6.
         Recommendations
      
      Inspection Officer
      
      In-Charge Station
      
      Names
         …………………………………………………..   Names
         ……………………………………………….
      
      
      
      2ps. 1ps.   Serial No …………….    Date of expiry ………...
      
      ## 5. Declaration
         by the applicant
      
      I, undersigned, declare that the particulars stated above
         are true and correct. 
      
      Names
         ………………………………………………………………  
         Signature …………………………………..
      
      ## 6.
         Recommendations
      
      Inspection Officer
      
      In-Charge Station
      
      Names
         …………………………………………………..   Names
         ………………………………………………. 
      
      Rank &amp; ID No.
         …………………………………………    rank &amp; ID No.
         ………………………………………..
      
      Signature, stamp and date
         …………………………..   Signature, stamp and date
         …………………………. 
      
      An original logbook or a certified
         photocopy must be presented at the time of inspection
      
      
      
      
    questions_and_answers:
      - question: |
          What type of application is Regulation 210 (1) focused on?
        answer: |
          Regulation 210 (1) pertains to the application for licensing vessels or vehicles for the conveyance of goods under customs control.
      - question: |
          What specific details are required regarding the motor vehicle in the application process?
        answer: |
          The application requires details such as the engine number, chassis number, vehicle registration number, model, color, year of manufacture, mileage, and the weight of the empty vehicle (tare).
      - question: |
          What documents related to the vehicle are mandated to be presented during inspection?
        answer: |
          An original logbook or a certified photocopy must be presented at the time of inspection.
      - question: |
          What information is required about the vehicle owner's contact details?
        answer: |
          The application requests the vehicle owner's name, P.O. Box number, telephone number, fax number, country of registration, and email address.
      - question: |
          What does the applicant need to declare in the application form?
        answer: |
          The applicant must declare that the particulars stated in the application are true and correct, accompanied by their name and signature.
document_outline: |
  **Document Outline:**  
  This document pertains to Regulation 210(1) under Customs, detailing the application process for licensing vessels or vehicles for the conveyance of goods under customs control. It includes sections for vehicle owner details, applicant information, motor vehicle registration, logbook and insurance details, a declaration by the applicant, and recommendations from the inspection officer and station in-charge.
document:
  repo: https://github.com/RIFAZ-SOLUTIONS/dataprepai.git
  commit: 1e7334d
  patterns:
    - c39-application-licensing-vessels-vehicles-conveyance-goods-under-customs-control.md
