version: 1
domain: tax
created_by: RIFAZ-SOLUTIONS
seed_examples:
  - context: |
      1ps. 1ps. ## IN THE COURT OF APPEAL OF TANZANIA AT PAR ES SALAAM CIVIL APPLICATION NO. 465/20 OF 2019 VODACOM TANZANIA PUBLIC CO. LTD.............................. APPLICANT ## VERSUS COMMISSIONER GENERAL (TRA)...................................RESPONDENT (Application for extension of time to lodge Memorandum and Record of Appeal out of time arising from the Judgment and Decree of the Tax Revenue Appeals Tribunal at Dar es Salaam) (Twaib, J.) dated the 6th day of April, 2011 in Tax Appeal No. 17 of 2010 ## RULING 26th February &amp; 10th March, 2020 ## LEVIRA, 3.A.: The applicant, Vodacom Tanzania Public Limited Company is seeking extension of 2ps. time within which to file an appeal to the Court against the decision of Tax Revenue Appeals Tribunal dated 6t h April, 2011 in Tax Appeal No. 17 of 2010. The Notice of Motion is made under Rule 10 of the Tanzania Court of Appeal Rules, 2009 (the Rules) and it is supported by the affidavit duly deposed by Sylivanus Mayenga, learned advocate. The application is not contested by 3ps. the respondent. 2ps. 1ps. APPLICANT ## VERSUS COMMISSIONER GENERAL (TRA)...................................RESPONDENT (Application for extension of time to lodge Memorandum and Record of Appeal out of time arising from the Judgment and Decree of the Tax Revenue Appeals Tribunal at Dar es Salaam) (Twaib, J.) dated the 6th day of April, 2011 in Tax Appeal No. 17 of 2010 ## RULING 26th February &amp; 10th March, 2020 ## LEVIRA, 3.A.: The application is not contested by the respondent. At the hearing of the application, the applicant was represented by Ms. Hadija Kinyaka, learned advocate. The respondent did not enter appearance and therefore, hearing proceeded 2ps. exparte under Rule 63(2) of the Rules. Ms.
    questions_and_answers:
      - question: |
          What legal relief was Vodacom Tanzania Public Limited Company seeking in this case?
        answer: |
          Vodacom Tanzania Public Limited Company was seeking an extension of time to file an appeal against the decision of the Tax Revenue Appeals Tribunal dated 6th April, 2011, in Tax Appeal No. 17 of 2010.
      - question: |
          Under which legal provision was the application for an extension of time made?
        answer: |
          The application for an extension of time was made under Rule 10 of the Tanzania Court of Appeal Rules, 2009.
      - question: |
          Who represented Vodacom Tanzania Public Limited Company during the hearing of the application?
        answer: |
          Vodacom Tanzania Public Limited Company was represented by Ms. Hadija Kinyaka, a learned advocate, during the hearing of the application.
      - question: |
          What was the respondent’s stance regarding the application for an extension of time?
        answer: |
          The respondent, Commissioner General (TRA), did not contest the application for an extension of time.
      - question: |
          What procedural rule allowed the hearing to proceed ex parte in this case?
        answer: |
          The hearing proceeded ex parte under Rule 63(2) of the Tanzania Court of Appeal Rules since the respondent did not enter an appearance.
  - context: |
      1ps. 1ps. In the present case the applicant had acted immediately after the pronouncement of the ruling of the Court striking out the first appeal. In these circumstances an extension of time ought to be granted . " In the current application, having gone through the record and the submission by Ms. Kinyaka, I now proceed to consider whether the reason for the delay advanced by the 2ps. applicant amount to good cause in terms of Rule 10 of the Rules. The said appeal was struck out on account of incompetence, as submitted by Ms. Kinyaka and clearly indicated under paragraphs 6 and 8 of the supporting affidavit. Paragraph 13 of the affidavit indicates that, the applicant was served with copies of the proper decision of the Tribunal on 11t h October, 2019. 3ps. From there time was spent in preparation, research and drafting of the application (paragraph 14). Having considered the reason for the delay advanced by the applicant, I am satisfied that the delay to lodge an appeal before the Court was not a result of applicant's negligence. 2ps. 1ps. The said appeal was struck out on account of incompetence, as submitted by Ms. Kinyaka and clearly indicated under paragraphs 6 and 8 of the supporting affidavit. Paragraph 13 of the affidavit indicates that, the applicant was served with copies of the proper decision of the Tribunal on 11t h October, 2019. From there time was spent in preparation, research and drafting 2ps. of the application (paragraph 14). The defects in the Judgment and Decree of the Tax Revenue Appeals Tribunal spotted out by the Court were above the applicant's control as rightly, in my view, stated by Ms. Kinyaka.
    questions_and_answers:
      - question: |
          Why was the initial appeal struck out by the Court?
        answer: |
          The initial appeal was struck out due to incompetence, as indicated under paragraphs 6 and 8 of the supporting affidavit.
      - question: |
          When was the applicant served with copies of the proper decision of the Tribunal?
        answer: |
          The applicant was served with copies of the proper decision of the Tribunal on 11th October, 2019.
      - question: |
          What activities contributed to the delay in lodging the new application?
        answer: |
          Time was spent on preparation, research, and drafting the application, as stated in paragraph 14 of the affidavit.
      - question: |
          What was the Court's determination regarding the applicant's delay in lodging an appeal?
        answer: |
          The Court was satisfied that the delay in lodging the appeal was not due to the applicant's negligence.
      - question: |
          What was the nature of the defects in the Judgment and Decree of the Tax Revenue Appeals Tribunal?
        answer: |
          The defects in the Judgment and Decree of the Tax Revenue Appeals Tribunal were beyond the applicant's control, as noted by Ms. Kinyaka and supported by the Court.
document_outline: |
  **Document Outline:**  
  This document details a ruling by the Court of Appeal of Tanzania on an application by Vodacom Tanzania Public Co. Ltd. for an extension of time to file an appeal against a Tax Revenue Appeals Tribunal decision from April 6, 2011. The court examines whether the delay in filing the appeal constitutes "good cause" under Rule 10 of the Tanzania Court of Appeal Rules, 2009, focusing on technical delays caused by procedural irregularities in the earlier appeal.
document:
  repo: https://github.com/RIFAZ-SOLUTIONS/dataprepai.git
  commit: 1e7334d
  patterns:
    - Vodacom_Tanzania_Public_Co_T_Ltd_vs_Commissioner_General_TRA_(Civil_Application_465_of_2019)_2020_TZCA_64_(10_March_2020).md
