version: 1
domain: tax
created_by: RIFAZ-SOLUTIONS
seed_examples:
  - context: |
      1ps. 1ps. For this reason, the applicant applied for extension of time through Civil Application No. 40/20 of 2018. That application was granted on 23/4/2018, and consequently, the application at hand was filed. Before we proceeded to determine the application, we found it apposite to consider the nature of the application as presented by the applicant. Firstly, as stated above, the applicant is seeking to be granted leave to 2ps. file supplementary record consisting of the omitted documents. Secondly, in the title of the notice of motion and the affidavit, it is shown that the application is "for leave to amend the Record and Memorandum o f Appeal in an appeal against the Judgment and Decree o f the Tax Revenue Appeals Tribunal at Dar es Salaam When Mr. Mayenga was asked to clarify on that mix-up, he conceded that, because what is sought 3ps. is inclusion of the omitted documents, the process does not amount to amendment of the record. 2ps. 1ps. Before we proceeded to determine the application, we found it apposite to consider the nature of the application as presented by the applicant. Firstly, as stated above, the applicant is seeking to be granted leave to file supplementary record consisting of the omitted documents. In our view, that is a correct position because under Rule 111 of the 2ps. Rules which vests the Court with the powers of ordering amendment of documents, the amendment envisaged in that Rule involves the documents such as; a notice of appeal, memorandum of appeal or a notice of cross-appeal which are contained in an already filed record of appeal. The provision does not allow for introduction of the documents which were not in the record at the time 3ps. of filing the appeal.
    questions_and_answers:
      - question: |
          Why did the applicant file Civil Application No. 40/20 of 2018?
        answer: |
          The applicant filed Civil Application No. 40/20 of 2018 to request an extension of time, which was granted on 23/4/2018, allowing for the current application to be filed.
      - question: |
          What is the applicant seeking permission for in the current application?
        answer: |
          The applicant is seeking leave to file a supplementary record consisting of omitted documents.
      - question: |
          Did the title of the notice of motion accurately reflect the nature of the application?
        answer: |
          No, the title of the notice of motion and the affidavit mentioned 'leave to amend the Record and Memorandum of Appeal,' but the process was clarified to involve the inclusion of omitted documents, not an amendment of the record.
      - question: |
          What does Rule 111 of the Rules allow regarding amendments to documents?
        answer: |
          Rule 111 of the Rules allows the Court to order the amendment of documents like the notice of appeal, memorandum of appeal, or notice of cross-appeal, provided these are already part of the filed record of appeal.
      - question: |
          Does Rule 111 permit the introduction of new documents not in the record at the time of filing the appeal?
        answer: |
          No, Rule 111 does not permit the introduction of documents that were not included in the record at the time of filing the appeal.
  - context: |
      1ps. 1ps. 25th &amp; 28th June, 2018 ## MWARIJA. J.A.: The applicant, ACE Distributors Limited has, by a notice of motion, brought this application seeking an order granting it the following:- "... leave to file supplementary record o f appeal by including the respondent's reply to statements o f appeal before the Tax Revenue Appeals Board and the Tax Revenue Appeals Tribunal and the parties' correspondences during objection proceedings (the documents) which were not included 2ps. in the record o f appeal lodged by the Applicant on 4 h October, 2017." ## IN THE COURT OF APPEAL OF TANZANIA AT DODOMA ## fCORAM: JUMA. CJ.. MWARIJA. J.A.. And MZIRAY. J.A.J CIVIL APPLICATION NO. 163 /20 OF 2018 ACE DISTRIBUTORS LIMITED.......................................................APPLICANT VERSUS THE COMMISSIONER GENERAL TANZANIA REVENUE AUTHORITY.............................................. RESPONDENT (Application for leave to amend the Record and Memorandum of Appeal in an appeal against the Judgment and Decree of the Tax Revenue Appeals Tribunal at Dar es Salaam) (Mataka. 2ps. 1ps. J.A.. And MZIRAY. J.A.J CIVIL APPLICATION NO. 163 /20 OF 2018 ACE DISTRIBUTORS LIMITED.......................................................APPLICANT VERSUS THE COMMISSIONER GENERAL TANZANIA REVENUE AUTHORITY.............................................. RESPONDENT (Application for leave to amend the Record and Memorandum of Appeal in an appeal against the Judgment and Decree of the Tax Revenue Appeals Tribunal at Dar es Salaam) (Mataka. Vice Chairperson^ Dated the 15th day of October, 2011 in VAT Appeal No. 13 of 2010 ## RULING OF THE COURT The application, which was brought under Rules 96(6) and 4(2)(a) and (b) of the Tanzania Court of Appeal Rules, 2009 (the Rules), 2ps. is supported by the affidavit of Sylivastus Sylivanus Mayenga, advocate. At the hearing on 25/6/2018, the applicant was represented by Mr. Sylivanus Mayenga, learned counsel whereas the respondent, The Commissioner General (TRA), was represented by Mr. Harold Gugami, learned counsel.
    questions_and_answers:
      - question: |
          What specific relief was the applicant seeking in the application before the Court of Appeal of Tanzania?
        answer: |
          The applicant, ACE Distributors Limited, sought leave to file a supplementary record of appeal to include the respondent's reply to statements of appeal, the parties' correspondences during objection proceedings, and other documents not included in the initial appeal filed on October 4, 2017.
      - question: |
          Under which rules of the Tanzania Court of Appeal Rules, 2009, was the application brought?
        answer: |
          The application was brought under Rules 96(6) and 4(2)(a) and (b) of the Tanzania Court of Appeal Rules, 2009.
      - question: |
          Who represented the applicant and the respondent during the hearing of the application on June 25, 2018?
        answer: |
          The applicant, ACE Distributors Limited, was represented by Mr. Sylivastus Sylivanus Mayenga, while the respondent, the Commissioner General of the Tanzania Revenue Authority, was represented by Mr. Harold Gugami.
      - question: |
          What is the case designation of the civil application filed by ACE Distributors Limited?
        answer: |
          The case is designated as Civil Application No. 163/20 of 2018.
      - question: |
          What was the original appeal that this application sought to amend, and when was the decision it challenged delivered?
        answer: |
          The application sought to amend the record and memorandum of appeal related to VAT Appeal No. 13 of 2010, with the challenged decision being delivered on October 15, 2011.
  - context: |
      1ps. 1ps.  Complete in  the sense  that it contains all the  essential  documents 
         itemized  under  Rule  89(1).  Under  Rule  92(1)  the  use  o f the  words 
         containing copies o f  any further documents or additional parts o f
         documents  which are,  in his opinion required for the proper determination 
         o f the  appeal' mean,  in  effect, that  the  supplementary  record  o f 
         appeal  may  be lodged for the purpose o f
      
      2ps. making good deficiencies in the record o f appeal not affecting the competence o
         f the appeal. 
      
      On  the basis  of  the above  stated position, inclusion of 
         the  omitted documents cannot be  made through  a  supplementary  record. 
         The same are  to  be  lodged  and  served  in  accordance  with  the 
         procedure  of  filing documents after institution of an appeal. 
      
      That having
         been said, we  hereby  grant  the application.  The applicant is granted 
         leave
      
      3ps. to  include the  omitted  documents  in  the  record of appeal.  It  has to do
         so within  14 days from the date of delivery of this ruling. 
      
      Each party
         shall bear its own costs.
      
      
      
      2ps. 1ps.  The applicant is granted  leave to  include the  omitted  documents  in  the 
         record of appeal.  It  has to do so within  14 days from the date of delivery
         of this ruling. 
      
      Each party shall bear its own costs. 
      
      DATED at DODOMA this
         27th  day of June, 2018.
      
      ## I.H. JUMA CHIEF JUSTICE
      
      A.G.MWARIJA JUSTICE OF
         APPEAL
      
      R.E.  MZIRAY
      
      <!-- image -->
      
      6
      
      
      
      
    questions_and_answers:
      - question: |
          What is the significance of Rule 89(1) in the context provided?
        answer: |
          Rule 89(1) states that a record of appeal must be complete, containing all the essential documents itemized under the rule.
      - question: |
          What does Rule 92(1) allow concerning supplementary records of appeal?
        answer: |
          Rule 92(1) allows the lodging of supplementary records of appeal to include additional documents necessary for the proper determination of the appeal.
      - question: |
          Why can't omitted documents be added through a supplementary record of appeal?
        answer: |
          Omitted documents cannot be added through a supplementary record because they must follow the procedure for filing documents after the institution of an appeal.
      - question: |
          What leave was granted to the applicant concerning omitted documents?
        answer: |
          The applicant was granted leave to include the omitted documents in the record of appeal, provided this is done within 14 days from the date of the ruling.
      - question: |
          Who delivered the ruling and on what date?
        answer: |
          The ruling was delivered by I.H. Juma (Chief Justice), A.G. Mwarija (Justice of Appeal), and R.E. Mziray on June 27, 2018, at Dodoma.
document_outline: |
  ### Document Outline:
  
  This document outlines a legal ruling in the Court of Appeal of Tanzania regarding ACE Distributors Limited's application to include omitted documents in its appeal against the Commissioner General of the Tanzania Revenue Authority. The Court granted the unopposed application after clarifying procedural requirements and acknowledging the applicant's previous extension of time to file the present motion.
document:
  repo: https://github.com/RIFAZ-SOLUTIONS/dataprepai.git
  commit: 1e7334d
  patterns:
    - Ace_Distributors_Ltd_vs_Commissioner_General_Tanzania_Revenue_Authority_(Civil_Application_No_16320_of_2018)_2018_TZCA_43_(28_June_2018).md
