version: 1
domain: tax
created_by: RIFAZ-SOLUTIONS
seed_examples:
  - context: |
      1ps. 1ps. ## IN THE HIGH COURT OF TANZANIA (COMMERCIAL DIVISION) ## AT PAR ES SALAAM MISC. COMMERCIAL CAUSE NO. 73 OF 2021 IN THE MATTER OF THE ARBITRATION ACT, CAP. 15 R.E. 2020 AND IN THE MATTER OF AN ARBITRATION UNDER THE INTERNATIONAL COURT OF ARBITRATION OF THE INTERNATIONAL CHAMBER OF COMMERCE ARBITRATION RULES 2017 (ICC Rules) ## AND IN THE MATTER OF APPLICATION FOR RECOGNITION AND ENFORCEMENT OF FOREIGN ARBITRATION AWARD BETWEEN FLEET MONITORING SYSTEMS LIMITED (UGANDA)...................PETITIONER VERSUS TANZANIA REVENUE AUTHORITY............................................... RESPONDENT THE ATTORNEY GENERAL................................................... NECESSARY PARTY Date of last order; 3/2/2022 Date of judgement 14/2/2022 ## CONSENT JUDGEMENT ## MAGOIGA, J. The petitioner, FLEET MONITORING SYSTEMS LIMITED (UGANDA) 2ps. by way of petition, instituted the instant petition against the above-named respondents, praying for confirming award against the respondent and enter consent judgement in favour of the applicant in the following order:- <!-- image --> - 1. That the Tanzania Revenue Authority to pay Fleet Monitoring Systems Limited the cumulative sum of USD.230,526.21 being final and conclusive settlement of the award as granted by Arbitral Tribunal. 2ps. 1ps. 15 R.E. 2020 AND IN THE MATTER OF AN ARBITRATION UNDER THE INTERNATIONAL COURT OF ARBITRATION OF THE INTERNATIONAL CHAMBER OF COMMERCE ARBITRATION RULES 2017 (ICC Rules) ## AND IN THE MATTER OF APPLICATION FOR RECOGNITION AND ENFORCEMENT OF FOREIGN ARBITRATION AWARD BETWEEN FLEET MONITORING SYSTEMS LIMITED (UGANDA)...................PETITIONER VERSUS TANZANIA REVENUE AUTHORITY............................................... RESPONDENT THE ATTORNEY GENERAL................................................... NECESSARY PARTY Date of last order; 3/2/2022 Date of judgement 14/2/2022 ## CONSENT JUDGEMENT ## MAGOIGA, J. When this case called for mention for orders on 3rd February, 2022, Ms. Violate Mipawa Learned Advocate for the Petitioner and Mr. David Kakwaya, Principal State Attorney for the respondents, informed the court on 2ps. the intention of the parties, to settle the matter out of court.
    questions_and_answers:
      - question: |
          What was the main legal issue in the case between Fleet Monitoring Systems Limited and Tanzania Revenue Authority?
        answer: |
          The case concerned the recognition and enforcement of a foreign arbitration award under the ICC Arbitration Rules 2017, with Fleet Monitoring Systems Limited seeking a payment of USD 230,526.21 awarded by an Arbitral Tribunal.
      - question: |
          What was the method of dispute resolution referenced in the case?
        answer: |
          The dispute was resolved through arbitration under the International Court of Arbitration of the International Chamber of Commerce (ICC) Arbitration Rules 2017.
      - question: |
          What was the court's decision on February 14, 2022?
        answer: |
          The court issued a consent judgement confirming the arbitration award and ordering the Tanzania Revenue Authority to pay Fleet Monitoring Systems Limited USD 230,526.21 as a final settlement.
      - question: |
          Who were the parties involved in the case?
        answer: |
          The petitioner was Fleet Monitoring Systems Limited (Uganda), the respondent was the Tanzania Revenue Authority, and the Attorney General of Tanzania was named as a necessary party.
      - question: |
          What was the intention of the parties mentioned on February 3, 2022?
        answer: |
          On February 3, 2022, both parties informed the court of their intention to settle the matter out of court.
  - context: |
      1ps. 1ps. 
      
      This provision was defined by Mulla, the code of civil procedure Act of 1908
         (14th ed) on page 1828, who stated that.  Therefore, by a deed of settlement
         dully executed by the parties in this case and filed in this court, this
         court hereby record this suit to be settled out of court in the terms and
         conditions as agreed in the deed of settlement under Order XXI1 Rule 3 of the
         Civil procedure. 
      
      It's so ordered. 
      
      Dated at Dar es salaam on this 14th
         February, 2022
      
      <!-- image -->
      
      <!-- image -->
      
      S.M. MAGOIGA JUDGE 14/2/2022
      
      
      
      
    questions_and_answers:
      - question: |
          What was the legal provision referenced in this case?
        answer: |
          The legal provision referenced was the Code of Civil Procedure Act of 1908, as defined by Mulla in its 14th edition on page 1828.
      - question: |
          How was the suit resolved according to the document?
        answer: |
          The suit was resolved out of court through a deed of settlement duly executed by the parties and filed in the court.
      - question: |
          Under which specific rule of the Civil Procedure was the settlement recorded?
        answer: |
          The settlement was recorded under Order XXIII Rule 3 of the Civil Procedure.
      - question: |
          Who presided over the case and ordered the settlement?
        answer: |
          The case was presided over and ordered by Judge S.M. Magoiga.
      - question: |
          What was the date and location of the court’s decision?
        answer: |
          The decision was dated 14th February 2022 in Dar es Salaam.
document_outline: |
  **Document Outline:**  
  This document outlines a consent judgment from the High Court of Tanzania (Commercial Division) in Misc. Commercial Cause No. 73 of 2021, wherein Fleet Monitoring Systems Limited (Uganda) petitioned for the recognition and enforcement of a foreign arbitration award against the Tanzania Revenue Authority. The case was resolved through a deed of settlement filed by the parties, with the court ordering the settlement terms to be recorded as a final resolution under Tanzanian Civil Procedure law.
document:
  repo: https://github.com/RIFAZ-SOLUTIONS/dataprepai.git
  commit: 1e7334d
  patterns:
    - Feet_Monitoring_system_Limited_(_Uganda)_vs_Tanzania_Revenue_Authority_Another_(Misc_Application_Cause_73_of_2021)_2022_TZHCComD_46_(14_February_2022).md
