version: 1
domain: tax
created_by: RIFAZ-SOLUTIONS
seed_examples:
  - context: |
      1ps. 1ps. ITX260.02.E   Application for Fund Refund of Negative net
         amount
      
      ![Image](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA0EAAAFPAQMAAACxplfDAAAABlBMVEUAAAD///+l2Z/dAAAMNUlEQVR4nO3cz49cNx0A8O/rq2KQQl4R16gOSFxRJSTIIVpXQoIjEheOzZ8Q1EMDhNhpkIJExfTAufMncEG9rqOA9lIxF24VnRdWaI/rYZDWyzo236/9ZmZndzZZb+MBIT+l253Z9/x5tr/+8X5C2NKioEpVqlKVqlSlKlWpSlWqUpWqVKUqValKVapSlapUpSpVqUpVqlKVqlSlKlWpSlWqUpWqVKUqValKVapSlapUpatJfmuSlVfRriIZlJzYhtSj4rptSJoktg0JSGq2IHmQGBXZ211BchB/yPKSaaLEy0t9Sz+hKy8ptvpZVkq50bnBly9RDWFf1OdumC9ZbE5OBpMbfPlSj4QV+cGXL2ncwvD84MuXAIO8R0m1hSUPLEk6c8tsyVKpUen1mSGRLRmKBCNSDBaVNAEkucyQyJYUPIS4PIS8/ihbgsYm6buQ1x/lSg7Yx0lqM4MvV8LQU0limcGXK5mVZPKCL1fSwPUg2bzgy5UUyP3UcjufF3yZkgcIz5LEQl7wZUoOU3+6kPK2zZbYStJZwZctdeHPUfI/zRx2syW+kN7DtlVUEuGvSfq8vPT7rUgepT9GyX2O9ZSzabbEw6dbll5sQfqe3Jb0/SRNtyb9rbz0gYi90dakk/KS/2A3Si+tJ38Xzi+ZUuffj9LRF0vpww2pblqypXmUQpL0xjSvfeu35zZ9Wen9690zCTRJGkdpvJB+ML3UTkbp6N5bl8p+m6RpLL1PsiPipctXYLa2OkouSeETeWWpmbx6dZRezCckHY7lxoPq6d8v3O2c/UrSYZSmUdKXKvYc6Vd3zFBPgzR5LdI/fvLuxlVj7B0naToOudLmRF8phfFu3+RJGUuUTuZHKU//C9J3xIZTz+pKku7CLtYTSbfek5eLqSzpG0maU8+yOx3nnQ67SLrL/zDdsDpK8/ncNxh140tJ/her8v3qpyJjz4AdzU98CxJLb106PHpV+WQwSTqJkphO9WVij8lhy8uNuf8OM9qqHaTQgJTT6abYe/OeuCCNjdJFOxqlg5NjlIJMebr88qqyXS7Ns18ehiS9wK28nE5eg/RNH6YXrA/skKTGh/FhrnSUs3qUHLZZ3JdsKQtaSK0LZ6P89Ut7cxd06+T1J6UlrFmpmaVTVGWlFiNGqHZrEp3kY6qw9GuSwN+CLu88dvYZqhZnWQH/vQO8vNR4DIq3ykvzJH1cXppB60BhVYnikmrd17YiWWCOW6Eh8xpKvoRTCTsOIuRercmX8IcNgW9HOg7bytP/sQRlpWZbUrxAkyS/HYnTZZvCklhIfdHrGih1C0mVltpBwqGjsAQySba8xFO/Z8pLLEm6vATBSi88bEES7m0n7DakzmFYGPqlpNTToSHNjWLmSkqOjuRIov9nbZl/3R2XmwAPcqvpKnct4AE6wDu51ZQtjczqcFjsl5Qeu5VE15DLSU9XR/sslG1PMsZ5alZlJU6dQ0MZk6YrKfXMD1JD5xMLSvuwqCiWeb9WrjTvxRDnwrGi0sx2Q5zLnvOikqf+NbYmLYtKJqiQzsIF8EUlG3qRJMe8KCvZDhn8Z3lpyS8lV1Ry0g2S4U6WlTRKLUmstAQ3UMJ+wjS2rLSzlNT9opLfuYYSw1FjZu5lbZkvwUdJ+pktLN2k+Uob+/N3ikrh5moeUVby/x1JlpTcHRza3/jhj4OQ7rYoKdk7IhyFSUKLSuaBwPnDhzyMMeB5SanHzg6Y6lwXvOhKStphnhgwlNydotKjKKnWonS7qKRI6h63lgV/S5SU9B0RjHjymKSydxPb6yjJx61pg897ECC7jwCSFCOp8NGnkgvJ8bJST3kC1jchbxJ2hWcbSPqwRckVlhxJbJsSbEd68lhD8Xryg9STWVbi9PPgmaHY2IJES94U9goSDkyJMIWlcOpszrakzIfv8iUdmW/v5m6XL111qVKVqlSlKlWpSlWqUpWqFBc89omLhts4ib8OrW1er7T7PlNgoKMHYRxdtNTxAv11YO71SJ5extHpaxCvrdxDQfWSLvLh16aFux3wwK4qWUZvJriXjtfoKBulG3RQpRsHwjPLg+JK2sZweNApHkZZkgIfE7dN6FuS7ifJ0Ws/pN1pNW/6NoB0dPZUCy1cayTITl9Cmgd6bh9iWXC624MStxBsp9vwCHc/SnRHVXAPMcVHhqFkucc6Ej1HCT+OUOIbpTG9hcdgHYrwPEksRIlR4jvoSccxyWf4S09FOUhc86ckBcN9S1I3SH03SF9Q4lgkpjXxUYkRFYZp6Slzkhzcx+2Y6XQ3JI41ITDJfUqUpA4Pf1ESmj+PUi9CM0gzlCZ954UCuguBx/u8ksRC6OjMp+/QjpIHjxWDRY+7thcTB76U7Lo0i6WHEqBkFpJhK6mjbLjOdD2jh+bpvUzcYvZ0lGg3O88HyWJYLSVHxTtIcpDo/VFqkOb4cULXFFHawUikNo1FwnuJqdFpT4xLrM4k4bpA3+N+RMkF1a1L7Kwkg5IosSQd2ha3gf5h4yhUYpH0YSF1SVIySoqkEaYySRJbSvT0Vr+UxHEsPTVImKeTQG+/abEc4LlvPB+yIZ4HDEg6aazPSIIkyzBYzkgPQ3q3EklYYCcxTySJJAWSXHO8kFzKhtgnKZYaOy9NsOJGMXHVemGTtLOSJG2MklpI/UqaobSPgZUSZSQpEd/Qhe0yfhnv/UrSAUk8SU3M0wF+oL//qVmTALuFdcnDfCHZQTogiaJbN+clyiyPiX8EMU8oxROXn10gab6UMAtwgNKYElctSVR/sJR8fIvRUmpI8klK9RSl352RKBFyqN+LUoAfLSR6M5dqUPKD9Bkk6dZK2gtYoyIm/jt4OEguSrBBwq4JwlJiSwnX/Q2VC7bSMMO//QUkSe5ut2xPe9RZiJj4CHYGKZ4i5aclusUlSdAsJYw27PdQCv/EdT8iiaJhHiWxJmE7ezJIlqS3B+lukuRSsqcktpTwD4O0D1QGkkdpH4N0kiQb75PCzhslap507Q4TH6mFRBGDfdpKMq1fSG+1G6QD/DjCxAMF4QHG30TxJNEFGcDf4l3K8EDGxEf6xrokzsUeSrdXUr+U9lSUcJTGP+1hBznRHUnHNkp32Rmpv3aqnrxcl5RMsXen2SjFbIjYWe7hBhPNSJpRHgN19lFSt/GDwZ0yb5yKPYdd3CbpJmyQRoqKpOPUwQYajCd9ktxS6hYSxZ6BoTfySeLnJGy5b2+UaE6BiSeJ+jjTkrQf3x0I2N9SlAdNEiY+snCq5dpzUur3MCTPS2OSMHFaN4xjb9pEyUepX0hfHyS3yBP1e5Zu7lxG+UJCHsR5icdBYZA4jXgWSNqjlowSRgT2RvHZX0p85F8mAUUISUpQkaxLaVDA6sB1AhXMnjstYUQmqV1Jw/gkxsPc6XSe0ujOFT+Xp9hfTlySPE2wkKDVdJw5gl2XxjhKLfPEcU5o2Ho9DZLuLpCo4wb5wtNMDEdxkhTE/pEmrd3BPLY2CJKPcI/SqEHPU+xTe48zikWe0iyM9+eleFxAEs0ZB0mdkmii2R3Nh6lJECNsLpgkTV8wPg5Iwjn4SjI8SWyTlLKB1XLsONbjIKWKSxLte5T8OcmdkXBSiyXPTbuICN2tS4qMY0fd7F7QSaJXf9L0OM7A0hSSpF64YaIk8HvcQIlZWPZ7tqN5OUr2rGRp3REl3mAHRIPUXqDpO1YChT2OGuKU5FAy1FRo+mIHSeO8KvXlNHGk+ycUToINpJcPQjtIx4MksMBnxyTROyIczoDiq/YG6Ul8gyolPsL/fBzqZS/pexpVnsUBr28psBojPOCR1Lu4YXxFQzNIs5R4TzOX5zNKbZBk7J5wdKemzZKEkRUlwGki0NDE6E1HBtiQ4P141CkdSUBSuhNgTTLUkp6SJLGkUHJRwr9pnP1jxXg6fBEgGVUP3RJLAywWR4/NC3OCHwfJnL/PIEn7KRsW4zI82k+S47YhKd5yoZlmZMbU4EG8vK/SYweSig6r5lX3ZawkOSKp881zmuU9IYnGOZzMYp32dM9ZNzx6gntNDRY7QQtv/nyR0quex1YUHFGKieu2b57SLA9rkfdwq6MXnRl6Lx1ECaed0Ixpw930XNfllyjJR1T8lLimuzWlhetYFvRhkDqblehFksED2Jh4iIm3iw/jL5/6GUnDDarbAomflba0VOlLSf8B3L4SQXknKz0AAAAASUVORK5CYII=)
         
      
      *(Under Regulation 29(1)(a))*
      
      **TO:	Commissinioner for Domestic
         Revenue/Large Taxpayer Department**
      
      **PO BOX ……………..**
      
      **DAR ES
         SALAAM**
      
      **U.f.S:  The Regional Manager**
      
      **Po
         Box………...............................................**
      
      **…………………………………………………**
      
      **APPLICATION
         FOR  REFUND OF NEGATIVE NET AMOUNT**
      
      I…………………………..(the 
         name of business) with VAT Registration Number
         (VRN)……………………………… and TIN
         ……………………………………………am satisfied that my input
         tax allowable credits exceeds the output tax   I made for the prescribed tax
         period(s) of……………………………..(state  month(s)and
         year).According to my computations, I have a net negative amount of
         Tshs………………………………………...........................................................
         
      
      I therefore apply to be refunded the entire amount
         **……………………………………………………**
      
      **.................................................
           
         ..............................................................		.........................**
      
      **Full
         Name   				Title
      
      2ps. of Applicant			  Date**
      
      **NOTE:-** To be submitted in triplicate
      
      
      
      
    questions_and_answers:
      - question: |
          What is the purpose of the application described in the document?
        answer: |
          The purpose of the application is to request a refund for a negative net amount, which occurs when allowable input tax credits exceed output tax for the prescribed tax period(s).
      - question: |
          Who is the primary recipient of the application?
        answer: |
          The primary recipient of the application is the Commissioner for Domestic Revenue, specifically the Large Taxpayer Department, as indicated in the address.
      - question: |
          What information is required about the applicant's business in the application?
        answer: |
          The application requires the business name, VAT Registration Number (VRN), Taxpayer Identification Number (TIN), and the specific months and years for which the net negative amount is being claimed.
      - question: |
          What must the applicant include to specify the amount being claimed?
        answer: |
          The applicant must compute and state the net negative amount of Tshs (Tanzanian Shillings) being claimed for the refund.
      - question: |
          How should the application be submitted according to the note at the end?
        answer: |
          The application should be submitted in triplicate, as mentioned in the note.
document_outline: |
  **Document Outline:**
  
  The document "ITX260.02.E Application for Fund Refund of Negative Net Amount" appears to contain procedural and administrative information for processing applications related to refunding a negative net amount. It might include guidelines, requirements, and processing steps for submitting and handling such requests.
document:
  repo: https://github.com/RIFAZ-SOLUTIONS/dataprepai.git
  commit: 1e7334d
  patterns:
    - ITX260.02.E_-_Application_for_Fund_Refund_of_Negative_net_amount.md
