version: 1
domain: tax
created_by: RIFAZ-SOLUTIONS
seed_examples:
  - context: |
      1ps. 1ps. ## IN THE COURT OF APPEAL OF TANZANIA AT DAR ES SALAAM CIVIL APPLICATION NO. 108 OF 2005 In the Matter of an Intended Appeal ## BETWEEN MBEYA INTERTRADE COMPANY LTD …………… APPLICANT VERSUS THE COMMISSIONER GENERAL, TANZANIA REVENUE AUTHORITY ) ) ………… RESPONDENT (Application for extension of time to lodge record of appeal from the decision of the Tax Revenue Appeals Tribunal at Dar es Salaam) (Shangwa, J.) dated the 29 th day of January, 2005 in Income Tax Appeal No. 6 of 2003 ------------ ## O R D E R ## KAJI, J.A.: By a notice of motion the 2ps. applicant, Mbeya Inter Trade Company LTD, is moving the court for extension of time in which to lodge the appeal. The main ground is that, when leave to appeal to this court was granted on 23/6/2005, certificate for delay had already been issued. In other words the certificate for delay was issued before the applicant's application for leave had been granted. Leave was granted on 23/6/2005 and the applicant was supplied with a copy of the ruling on 1/7/2005. 2ps. 1ps. The main ground is that, when leave to appeal to this court was granted on 23/6/2005, certificate for delay had already been issued. In other words the certificate for delay was issued before the applicant's application for leave had been granted. Leave was granted on 23/6/2005 and the applicant was supplied with a copy of the ruling on 1/7/2005. Thereafter the applicant filed this application on 27/7/2005. There is nothing suggesting anelement of negligence for the short delay. The respondent is not opposing the application. Application 2ps. granted as presented. The applicant to file the intended appeal within fourteen days from to-day 2 nd day of December, 2005. Costs in the intended appeal.
    questions_and_answers:
      - question: |
          What is the main issue addressed in Civil Application No. 108 of 2005?
        answer: |
          The main issue concerns an application by Mbeya Intertrade Company Ltd for an extension of time to lodge an appeal against the decision of the Tax Revenue Appeals Tribunal.
      - question: |
          What justification did the applicant provide for the extension of time?
        answer: |
          The applicant argued that the certificate for delay was issued before their application for leave to appeal had been granted, and there was no evidence of negligence causing the short delay.
      - question: |
          On what date was leave to appeal granted, according to the court record?
        answer: |
          Leave to appeal was granted on June 23, 2005.
      - question: |
          When was the ruling supplied to the applicant after leave to appeal was granted?
        answer: |
          The ruling was supplied to the applicant on July 1, 2005.
      - question: |
          What decision did the court make regarding the application for an extension of time?
        answer: |
          The court granted the application and gave the applicant fourteen days from December 2, 2005, to file the intended appeal. The costs were to be determined in the intended appeal.
document_outline: |
  **Document Outline:**  
  The document is a court order from the Court of Appeal of Tanzania in Civil Application No. 108 of 2005, concerning Mbeya Intertrade Company Ltd's application for an extension of time to lodge an appeal against a decision of the Tax Revenue Appeals Tribunal. The court granted the application, noting no negligence in the short delay, and directed the applicant to file the appeal within 14 days.
document:
  repo: https://github.com/RIFAZ-SOLUTIONS/dataprepai.git
  commit: 1e7334d
  patterns:
    - Mbeya_Inter_Trade_Company_Ltd_vs_Commissioner_General_Tanzania_Revenue_Authority_(Civil_Application_108_of_2005)_2005_TZCA_91_(2_December_2005).md
