version: 1
domain: tax
created_by: RIFAZ-SOLUTIONS
seed_examples:
  - context: |
      1ps. 1ps. The applicant is not to blame for the delay as he was diligently pursuing his right and the delay was wholly occasioned by the trial court as it delayed in furnishing him with the ruling and drawn order even after close follow ups. As a result, there was nothing that he could do in pursuit of his right timely. He further cited the case of Ngoni-Matengo Cooperative Marketing Union 2ps. Ltd v Alimohamed Osman [1962] 1 E.A1 where the court held that the applicant should not be condemned by a mistake done by the registry which supplied him with a wrongly dated decree. Based on these authorities, she prayed that the application be allowed and the leave be granted. In his reply submission, Mr. Brian William Magoma, learned State Attorney, refereed the court the decision of 3ps. the Court of Appeal in Lyamuya Construction Company Ltd v Board of Trustees of Young Women's Christian Association of Tanzania, Civil Application No. 2 of 2010, where it stated the factors for consideration in determining an application for extension of time. 2ps. 1ps. He further cited the case of Ngoni-Matengo Cooperative Marketing Union Ltd v Alimohamed Osman [1962] 1 E.A1 where the court held that the applicant should not be condemned by a mistake done by the registry which supplied him with a wrongly dated decree. Based on these authorities, she prayed that the application be allowed and the leave be granted. He proceeded that section 14 2ps. of the Law of Limitation Act [Cap 89 RE 2019] vests this court with discretion in enlargement of time but the discretion need be judiciously exercised.
    questions_and_answers:
      - question: |
          Why was the applicant not blamed for the delay in pursuing his rights?
        answer: |
          The applicant was not blamed because the delay was caused by the trial court's failure to furnish him with the ruling and drawn order despite his diligent follow-ups.
      - question: |
          What precedent case was cited to support the argument that the applicant should not be penalized for the delay?
        answer: |
          The case of Ngoni-Matengo Cooperative Marketing Union Ltd v Alimohamed Osman [1962] 1 E.A1 was cited, where the court held that a party should not be condemned for a mistake made by the registry.
      - question: |
          What decision was cited by the learned State Attorney regarding factors for extension of time?
        answer: |
          The decision of the Court of Appeal in Lyamuya Construction Company Ltd v Board of Trustees of Young Women's Christian Association of Tanzania, Civil Application No. 2 of 2010, was cited.
      - question: |
          Which legal provision vests the court with the discretion to enlarge the time limits?
        answer: |
          Section 14 of the Law of Limitation Act [Cap 89 RE 2019] grants the court discretionary power to enlarge time limits.
      - question: |
          What was the applicant's prayer to the court based on the authorities cited?
        answer: |
          The applicant prayed that the application be allowed and leave be granted for the extension of time.
  - context: |
      1ps. 1ps. ## IN THE HIGH COURT OF THE UNITED REPUBLIC OF TANZANIA (MOSHI SUB REGISTRY) AT MOSHI ## MISC. CIVIL APPLICATION NO.18 OF 2022 (Originating from Civil Case No. 1 of 2022 before Moshi- RM's Court) SALVATORY NICHOLAUS MBISHI.................................APPLICANT VERSUS TANZANIA REVENUE AUTHORITY........................... RESPONDENT ## RULING Last Order: 31s t March,2023 Date of Ruling: 5th May, 2023 ## MASABO, J.:- The applicant being aggrieved by a decision of the Court of the Resident Magistrate for Moshi in C ivil Case N o . l of 20 2 2 , is desirous of appealing to this court. 2ps. As the time within which to file the appeal has lapsed, he has moved this court for leave to file his appeal out of time. The application is accompanied by an affidavit he has personally deponed in which the following background to the application and the reasons thereto are discerned. That, his suit was dismissed on 11/8/2022 after the court upheld a preliminary objection raised by the respondent asserting 3ps. that the court was not clothed with jurisdiction to entertain the suit. 2ps. 1ps. As the time within which to file the appeal has lapsed, he has moved this court for leave to file his appeal out of time. The application is accompanied by an affidavit he has personally deponed in which the following background to the application and the reasons thereto are discerned. That, his suit was dismissed on 11/8/2022 after the court upheld a preliminary objection raised by the respondent asserting 2ps. that the court was not clothed with jurisdiction to entertain the suit. After the dismissal of the appeal, he was not timely furnished with a copy of the ruling and drawn order. In spite of several followups, he was not furnished with the same until on 8/11/2022.
    questions_and_answers:
      - question: |
          What is the case Misc. Civil Application No. 18 of 2022 about?
        answer: |
          The case involves the applicant, Salvatory Nicholaus Mbishi, seeking leave from the High Court to file an appeal out of time after being aggrieved by the decision of the Resident Magistrate's Court in Civil Case No. 1 of 2022.
      - question: |
          Why was the applicant's original suit dismissed in the Resident Magistrate's Court?
        answer: |
          The suit was dismissed on 11th August 2022 after the court upheld a preliminary objection raised by the respondent, asserting that the court lacked jurisdiction to entertain the suit.
      - question: |
          Why did the applicant request an extension to file an appeal?
        answer: |
          The applicant requested an extension because the time to file the appeal had lapsed, and he was not provided a copy of the ruling and drawn order in a timely manner, despite making several follow-ups.
      - question: |
          When was the applicant finally furnished with the ruling and drawn order from the Resident Magistrate's Court?
        answer: |
          The applicant received the ruling and drawn order on 8th November 2022 after multiple follow-ups.
      - question: |
          Who is the respondent in Misc. Civil Application No. 18 of 2022?
        answer: |
          The respondent in the case is the Tanzania Revenue Authority.
  - context: |
      1ps. 1ps. With much respect to the learned State Attorney, I will not entertain this issue as it was improperly raised in the course of written submission. Besides, even if it was properly raised, it would definitely fail as it appears to be a mere clerical error curable by the principle of overriding objective enshrined under section 3A and 38B of the Civil Procedure Code [Cap 33 RE 2019]. Having resolved the above issue, I now turn to Mr. Magoma's 2ps. submission as regards whether this application was properly filed. The learned State Attorney has argued that, the present application was prematurely filed because the duration within which to appeal to this court had not lapsed when the applicant filed the present application in court. Cementing his argument, he has argued that, the duration within which to appeal from the 3ps. Court of the Resident Magistrate to this court is 30 days. 2ps. 1ps. Having resolved the above issue, I now turn to Mr. Magoma's submission as regards whether this application was properly filed. The learned State Attorney has argued that, the present application was prematurely filed because the duration within which to appeal to this court had not lapsed when the applicant filed the present application in court. Cementing his argument, 2ps. he has argued that, the duration within which to appeal from the Court of the Resident Magistrate to this court is 30 days. He has further, in fortification, cited the provision of section 19(2) of the Law of Limitation Act which provides for exclusion of the days within which the applicant was waiting to be furnished with the copy of the ruling. Based on this provision he has argued that, when the days within which the applicant was waiting to be furnished 3ps.
    questions_and_answers:
      - question: |
          What was the reason the writer refused to entertain the issue raised by the State Attorney?
        answer: |
          The writer refused to entertain the issue because it was improperly raised in the course of written submissions and would fail as it was a mere clerical error curable by the principle of overriding objective under sections 3A and 38B of the Civil Procedure Code [Cap 33 RE 2019].
      - question: |
          What argument did the learned State Attorney make regarding the timing of the application?
        answer: |
          The learned State Attorney argued that the application was prematurely filed because the 30-day duration to appeal from the Court of the Resident Magistrate to this court had not lapsed when the applicant filed the application.
      - question: |
          What legal provision did the State Attorney cite to support the exclusion of certain days in the filing timeline?
        answer: |
          The State Attorney cited section 19(2) of the Law of Limitation Act, which provides for the exclusion of the days during which the applicant was waiting to be furnished with the copy of the ruling.
      - question: |
          What is the principle of overriding objective mentioned in the text?
        answer: |
          The principle of overriding objective, as referenced in sections 3A and 38B of the Civil Procedure Code, allows for the correction of clerical errors to ensure justice and efficiency in legal proceedings.
      - question: |
          What event must occur within 30 days according to the Civil Procedure Code?
        answer: |
          According to the Civil Procedure Code, the appeal from the Court of the Resident Magistrate to this court must occur within 30 days.
  - context: |
      1ps. 1ps. Section 19(2) of the Law of Limitation Act which Mr. Magoma has cited in support of submission states thus; 19.-(2) In computing the period of limitation prescribed for an appeal, an application for leave to appeal, or an application for review of judgment, the day on which the judgment complained of was delivered, and the period of time requisite for obtaining a copy of the decree or order appealed from or sought to be reviewed, shall be excluded. Interpreting the above provision in Alex Senkoro, the Court of Appeal stated that; "We entertain 2ps. no doubt that the above sub-sections expressly allow automatic exclusion of the period of time requisite for obtaining a copy of the decree or judgment appealed from the computation of the prescribed limitation period. Such an exclusion need not be made upon an order of the court in a formal application for extension of time." 2ps. 1ps. It is in this context, section 19(2) of the Law of Limitation Act is coined to protect the appellant who would otherwise be wrongly condemned for a delay wholly occasioned by the court's failure to furnish him with the copy of judgment, ruling, decree or drawn order, as the case in point. Such an exclusion need not be made upon an order of the court in a formal application for extension of time." Also, the Court took the same stance in Methuselah Enoka 2ps. (supra), where it did not only acknowledge the automatic exclusion but also stated that there is no need for a separate application nor according any attachment to a memorandum of appeal.
    questions_and_answers:
      - question: |
          What does Section 19(2) of the Law of Limitation Act specify regarding the computation of the limitation period?
        answer: |
          Section 19(2) states that the day the judgment is delivered and the time required to obtain a copy of the decree or order should be excluded when computing the limitation period for an appeal, application for leave to appeal, or application for review of judgment.
      - question: |
          What did the Court of Appeal conclude in the case of Alex Senkoro regarding Section 19(2)?
        answer: |
          The Court of Appeal concluded that Section 19(2) allows for the automatic exclusion of the time required to obtain a copy of the decree or judgment without a formal court order or an application for an extension of time.
      - question: |
          How does Section 19(2) protect appellants according to the context provided?
        answer: |
          Section 19(2) protects appellants by ensuring they are not penalized for delays caused by the court's failure to provide copies of the judgment, ruling, decree, or order in time.
      - question: |
          Is a formal application required to exclude the time needed to obtain a copy of the decree under Section 19(2)?
        answer: |
          No, the exclusion under Section 19(2) is automatic and does not require a formal application or an order from the court.
      - question: |
          What additional clarification did the Court provide in the Methuselah Enoka case regarding Section 19(2)?
        answer: |
          In the Methuselah Enoka case, the Court emphasized that there is no need for a separate application or attaching any supporting documents to the memorandum of appeal for the exclusion to apply.
  - context: |
      1ps. 1ps.   Much as it is true that the time within which to file the appeal has lapsed
         and the said time was spent while pursuing the present application, it will
         be unjust to condemn and punish the applicant  who has been  diligently
         prosecuting  the present  application mistakenly believing that,  he was
         legally obliged  so.   It is in  my considered view that the delay occasioned
         while pursuing this application is a technical one and excusable as he has
         diligently pursued his right in this court.   The  costs 
      
      2ps. are to  be  shared  by each of the parties shouldering its respective costs.
         
      
      DATED at DELIVERED at MOSHI this 5th  day of May 2023.
      
      <!-- image
         -->
      
      <!-- image -->
      
      J.L. MASABO JUDGE
      
      CUURT
      
      
      
      
    questions_and_answers:
      - question: |
          What was the applicant mistakenly believing while prosecuting the present application?
        answer: |
          The applicant mistakenly believed that he was legally obliged to pursue the present application.
      - question: |
          Why was the delay in filing the appeal considered excusable?
        answer: |
          The delay was considered excusable because it was deemed a technical delay, and the applicant had diligently pursued his right in the court.
      - question: |
          What decision was made regarding the costs in this case?
        answer: |
          The costs are to be shared, with each party shouldering its respective costs.
      - question: |
          Where and when was this decision delivered?
        answer: |
          The decision was delivered at Moshi on the 5th day of May 2023.
      - question: |
          Who authored the judgment in this case?
        answer: |
          The judgment was authored by J.L. Masabo, Judge.
document_outline: |
  **Document Outline:**
  
  This document outlines a ruling from the High Court of Tanzania involving Misc. Civil Application No. 18 of 2022, where the applicant, Salvatory Nicholaus Mbishi, sought leave to file an appeal out of time against a prior decision by the Moshi Resident Magistrate's Court. The application, grounded in delays caused by the trial court's failure to furnish the applicant with the ruling and drawn order on time, was opposed by the respondent, Tanzania Revenue Authority, with arguments from both sides presented for the court's consideration.
document:
  repo: https://github.com/RIFAZ-SOLUTIONS/dataprepai.git
  commit: 1e7334d
  patterns:
    - Salvatory_Nicholaus_Mbishi_vs_Tanzania_Revenue_Authority_(Misc_Civil_Application_18_of_2022)_2023_TZHC_17217_(5_May_2023).md
